#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfea7;
constexpr uint24_t FX_DATA_BYTES = 84019;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Three_Inc = 0x00529F;
  constexpr uint24_t SFX_Three_Dec = 0x0052BB;
  constexpr uint24_t SFX_Death = 0x0052D7;
  constexpr uint24_t SFX_Victory = 0x00538B;
  constexpr uint24_t SFX_XPGain = 0x00543F;
}

namespace Images
{
  constexpr uint24_t Player_01_00 = 0x005453;
  constexpr uint24_t Player_01_01 = 0x005515;
  constexpr uint24_t Player_01_02 = 0x0055BF;
  constexpr uint24_t Player_01_03 = 0x005645;
  constexpr uint24_t Player_01_04 = 0x0056B3;
  constexpr uint24_t Player_01_05 = 0x0056FD;
  constexpr uint24_t Player_01_06 = 0x00573B;
  constexpr uint24_t Player_01_07 = 0x005779;
  constexpr uint24_t Player_01_08 = 0x0057B7;
  constexpr uint24_t Player_01_09 = 0x005801;
  constexpr uint24_t Player_01_10 = 0x00586F;
  constexpr uint24_t Player_01_11 = 0x0058F5;
  constexpr uint24_t Player_01_12 = 0x00599F;
  constexpr uint24_t Player_00_00 = 0x005A61;
  constexpr uint24_t Player_00_01 = 0x005B23;
  constexpr uint24_t Player_00_02 = 0x005BCD;
  constexpr uint24_t Player_00_03 = 0x005C53;
  constexpr uint24_t Player_00_04 = 0x005CC1;
  constexpr uint24_t Player_00_05 = 0x005D0B;
  constexpr uint24_t Player_00_06 = 0x005D49;
  constexpr uint24_t Player_00_07 = 0x005D87;
  constexpr uint24_t Player_00_08 = 0x005DC5;
  constexpr uint24_t Player_00_09 = 0x005E0F;
  constexpr uint24_t Player_00_10 = 0x005E7D;
  constexpr uint24_t Player_00_11 = 0x005F03;
  constexpr uint24_t Player_00_12 = 0x005FAD;
  constexpr uint24_t Player = 0x00606F;
  constexpr uint24_t HUD = 0x00608F;
  constexpr uint24_t PPOT = 0x008F71;
  constexpr uint24_t Sound_Volume = 0x00BF73;
  constexpr uint24_t Sound_Checkbox = 0x00C395;
  constexpr uint24_t Title = 0x00C3A3;
  constexpr uint24_t Numbers_5x3_1D_WB = 0x0123A5;
  constexpr uint24_t Numbers_5x3_2D_WB = 0x012401;
  constexpr uint24_t GameOver = 0x012C37;
  constexpr uint24_t Plus8 = 0x013779;
  constexpr uint24_t Quit = 0x014243;
  constexpr uint24_t Player_Rotate = 0x0147E5;
}

